Downgrade SDK to 23
Catbag/redux-android-sample pull request #27
Opened 2016-10-20 17:47 UTC by niltonvasques

* Refactor file downloader mocks in instrumented tests
* Fix gifLoadingTest

2016-10-20 17:50 UTC, fpbitencourt approved these changes
:-1:

2016-10-22 06:37 UTC, niltonvasques commented
@raulccabreu Do you can enable trusted settings in drone configs? We need this to run privileged containers in the builds and support KVM. Take a look in the PR infos.

2016-10-23 23:31 UTC, raulccabreu commented
The trusted options is now enabled.

2016-10-24 00:26 UTC, raulccabreu commented
Only to remeber, the first comment will go to docker image readme??

2016-10-24 00:32 UTC, niltonvasques commented
Yes! Part of that comment will go to docker image readme and other part will go in readme from that project.

2016-10-24 00:37 UTC, raulccabreu requested changes

2016-10-24 00:37 UTC, raulccabreu commented on .drone.yml
> +  image: niltonvasques/android-emulator:1.3
To remeber...change to central image repo...

2016-10-24 00:37 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        sleep(2000);
To remeber, change all sleeps to idling resource....probably a issue to be opened
```
// Make sure Espresso does not time out
IdlingPolicies.setMasterPolicyTimeout(waitingTime * 2, TimeUnit.MILLISECONDS);
IdlingPolicies.setIdlingResourceTimeout(waitingTime * 2, TimeUnit.MILLISECONDS);

// Now we wait
IdlingResource idlingResource = new ElapsedTimeIdlingResource(waitingTime);
Espresso.registerIdlingResources(idlingResource);

// Stop and verify
onView(withId(R.id.toggle_button))
    .check(matches(withText(R.string.stop)))
    .perform(click());
onView(withId(R.id.result))
    .check(matches(withText(success ? R.string.success: R.string.failure)));

// Clean up
Espresso.unregisterIdlingResources(idlingResource);
```

2016-10-25 21:30 UTC, raulccabreu requested changes

2016-10-25 21:30 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/GifListActivity.java
> +    private GifWrapper mGlideWrapper;
Glide reference...

2016-10-25 21:30 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/GifListActivity.java
> +    public GifWrapper getGlideWrapper() {
Glide reference....

2016-10-25 21:30 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/wrappers/GifWrapper.java
> +    private GlideLoadListener mLoadListener;
Glide ref

2016-10-25 21:30 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/wrappers/GifWrapper.java
> +    public GifWrapper onException(GlideExceptionListener listener) {
Glide ref

2016-10-25 22:34 UTC, niltonvasques commented on .drone.yml
> +  image: niltonvasques/android-emulator:1.3
We can change the image, when we need change something in the image.

2016-10-25 22:59 UTC, raulccabreu approved these changes

2016-10-25 23:06 UTC, merged