Gif List with RecyclerView
Catbag/redux-android-sample pull request #32
Opened 2016-10-28 15:56 UTC by raulccabreu

- Data package with DatabaseManager and Database (simple fake seed).
- All gif items are async loaded by ActionCreator inside activity onCreate.
- Rename gifstate to gif.
- Old idlings removed.
- New UiTestLocker idling resource
- Change usage of error toast msg to red gif box red background
- Create FakeReducer to insert test cases initial app states
- Removed package mocks with everything inside
- Adjust GifListActivityTest to use a new way of testing: now we set an
  initial app state using a fake reducer (empty binded reduce that do
nothing but passes state to dispatcher), launch activity and
 1.immediatly test the UI presentation to the initial test case state or
 2. make a UI interaction, waits for app state change using an idling
resource and makes the final assertions.
- Create tests for scroll recycler up and down and perform clicks.
- Include espress-contrib for RecyclerView espresso test helpers.
- Add load list reducer test.
- Create a feed component using anvil(react) recyclerview to list gif items.
- The past gif view is now the GifComponent class that is a view item on RecyclerView.
- Create GifComponent static xml.
- Insert permission to use inline fors on PMD.
- Remove FileDownloader.onStart callback from gifDownloadStart method and change GIF_DOWNLOAD_STARTED action to GIF_DOWNLOAD_START.
- Move listeners in FileDownloader to internal download method.
- Fix downloading test setting a downloading state
- Fix download failure test setting a failed state
- Refactor responsabilities of the reducers by creating two reducers, one to be the main reducer (AppStateReducer) and other to be the inner reducer (GifReducer).
- Move all retrofit logic/items to FileDownloads as inner class.
- Renaming App to MyApp to make more clear that this object is a custom
 Application.

2016-10-28 21:39 UTC, niltonvasques requested changes
The project is growing on shape :smile_cat:

2016-10-28 21:39 UTC, niltonvasques commented on app/build.gradle
unused lines

2016-10-28 21:39 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        assertNotNull(gifView.getDrawable());
We have the withGifDrawable matcher to assert this.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        assertFalse(((GifDrawable)gifView.getDrawable()).isPlaying());
We have withGifDrawablePlaying matcher for it.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        private List<Gif> createFakeGifList(int size) {
Wrong ident. Checkstyle not identify it?

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/actions/GifActionCreator.java
> +        mFileDownloader.download(state.getUrl(), pathToSave,
the above comment is obsolete.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/actions/GifListActionCreator.java
> +        this.mDataManager = mDataManager;
m[A-Z][a-z] name pattern is to be used only for class attributes.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/downloader/FileDownloader.java
> +                    new Thread(() -> {
If we uses the retrofit callback executors we can always ensure that responses will not running in main thread. 
However, when any executors are created the response will run in mainThread.

Ref: https://square.github.io/retrofit/2.x/retrofit/retrofit2/Callback.html

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/downloader/FileDownloader.java
> +    private final class RoutesGenerator {
Later we will need extract this class from here.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/helpers/AppStateHelper.java
> +}
I'm thinking here, why those methods cannot be in AppState? AppState is a kind of Immutable DataStructure, and those methods looks fits very well there.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/components/FeedComponent.java
> +                mDrawables.put(gif.getUuid(), drawable);
Later we need improve the drawable cache, to avoid keep all those drawables on memory.

2016-10-28 21:39 UTC, niltonvasques commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/GifListReducerTest.java
> +    public List<Gif> getFakeGifs() {
private

2016-10-28 21:39 UTC, niltonvasques commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/GifListReducerTest.java
> +    public void dispatchSomeGifs() {
private

2016-10-29 01:12 UTC, fpbitencourt commented on app/src/main/java/br/com/catbag/gifreduxsample/actions/GifActionCreator.java
> +    public void gifDownloadStart(Gif state, Context context) {
A classe GifState foi renomeada para Gif porém em alguns métodos o parâmetro continuou sendo chamado de state, era bom manter o padrão e alterar para gif também.

2016-10-29 01:20 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        private List<Gif> createFakeGifList(int size) {
Check, but with lambda checkstyle has some problems...i will open a issue to solve this problem with more energy on future...see this: https://github.com/checkstyle/checkstyle/issues/281

2016-10-29 01:57 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/helpers/AppStateHelper.java
> +}
I don't have a strong opinion about this, maybe this object being simple and clear, with only immutable methods (that have yours own complexity) will be more easy to maintain and understand app model. Thinking that this objects will be more representative of all app information. Need a live discussion. Opening a issue.

2016-10-29 01:57 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/ui/components/FeedComponent.java
> +                mDrawables.put(gif.getUuid(), drawable);
issue....

2016-10-29 12:58 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/downloader/FileDownloader.java
> +    private final class RoutesGenerator {
i opened a issue to this before the PR

2016-10-29 13:00 UTC, fpbitencourt approved these changes

2016-10-29 20:59 UTC, niltonvasques approved these changes

2016-10-29 21:03 UTC, merged