Integrando database NOSQL ao projeto
Catbag/redux-android-sample pull request #57
Opened 2016-11-12 12:24 UTC by fpbitencourt

1. Setup SnnapyDB
2. Persistindo AppState
3. DataManager implementa StateListener e persiste o último estado modificado da app
4. Referência do DataManager centralizado no Application
5. DataManagerTest - whenAppStateChangesOnceTime and whenAppStateChangesSeveralTime
6. Novo Action 'APP_STATE_LOADED' para reduzir o estado inicial da app
8. Jackson para Serealizar e Desserealizar AppState e Gif
9. Implementado equals para as classes AppState e Gif
10. Setado multiDexEnabled, solução intermediária para o limite de métodos no projeto (https://github.com/Catbag/redux-android-sample/issues/56)

2016-11-12 15:05 UTC, niltonvasques requested changes

2016-11-12 15:05 UTC, niltonvasques commented on app/build.gradle
> +    compile 'com.github.trikita:anvil-recyclerview:1.2'
duplicated

2016-11-12 15:05 UTC, niltonvasques commented on app/build.gradle
> +    compile 'co.trikita:anvil-sdk15:0.4.0'
duplicated

2016-11-12 15:05 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
I guess that others methods from DataManager also should be tested.

2016-11-12 15:05 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
There is a subtle problem with AsyncTasks to perform background operations.

When a fresh AsyncTask is launched, it's auto bind the current activity on screen, and retains it's object even when the activity is finished. Which can leads to memory leaks.

There are several articles talking about the issues with AsyncTasks: 
- http://blog.danlew.net/2014/06/21/the-hidden-pitfalls-of-asynctask/
- http://simonvt.net/2014/04/17/asynctask-is-bad-and-you-should-feel-bad/
- http://bon-app-etit.blogspot.com.br/2013/04/the-dark-side-of-asynctask.html

2016-11-12 15:05 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/storage/Database.java
>  public class Database {
I would recommends to write simple unit tests for those methods, only to ensures the right behavior.

2016-11-12 15:05 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/models/AppState.java
> +    }
I would recommends to write simple unit tests for those methods, only to ensures the right behavior.

2016-11-12 15:05 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/models/AppState.java
> +    }
The default equals method that is generated by Immutable library isn'y enough? Why?

2016-11-12 15:05 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/reducers/AppStateReducer.java
> +    }
This new reduce action needs to be tested.

2016-11-12 15:08 UTC, fpbitencourt commented on app/src/main/java/br/com/catbag/gifreduxsample/models/AppState.java
> +    }
O pmd obriga/recomenda sobrescrever esse método sempre que o equals é sobrecarregado, ainda que seja só pra chamar o super.

2016-11-12 15:18 UTC, fpbitencourt commented on app/build.gradle
> +    compile 'co.trikita:anvil-sdk15:0.4.0'
Falha no merge. Será que as ferramentas de inspect não poderiam sinalizar isso?

2016-11-12 15:18 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
Quais?

2016-11-12 15:20 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
Probably all public methods.

2016-11-12 15:22 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
Concordo. Boa parte surgiu após puxar do integração com a master, por isso não olhei para eles. Abrirei uma issue para isso.

2016-11-12 15:23 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/models/AppState.java
> +    }
Hmm... Mas essa implementação é a mesma gerada pela lib immutables? Se sim, talvez seja adequado a gente dá um supress nesse warning do pmd. 
@raulccabreu pode dar um help com isso

2016-11-12 15:24 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
Na verdade, só vejo necessidade de fazer teste do _fetchGifs_

2016-11-12 15:25 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +public class DataManagerTest {
E qual a garantia temos de que os demais estão ok?

2016-11-12 16:49 UTC, fpbitencourt commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
Manolo, li os artigos mas não consegui compreender se ela é sempre _bindada_ à _actitivy_ atual. No caso atual, ela não é explicitamente associada à nenhuma activity. Fiz o teste encerrando a _activity_ atual e depois abrindo novamente enquanto a _asynctask_ executava em background e funcionou normalmente.

2016-11-12 16:56 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
Mas não vai crashar sempre. No entanto, ela fica segurando a activity que estava presente no momento que a async foi criada, mesmo após a activity já ter saido da tela. O que por sua vez gera memory leaks, já que o Garbage Colector não vai poder limpar o objeto da activity. Pra testar essa comportamento especifico da Async deve dá um trabalhozinho.

Veja: 

> Memory leaks
> Because an AsyncTask has methods that run on the worker thread (doInBackground()) as well as methods that run on the UI (e.g. onPostExecute()), it has took keep a reference to it's Activity as long as it's running. But if the Activity has already been destroyed, it will still keep this reference in memory. This is completely useless because the task has been cancelled anyway. ref: http://bon-app-etit.blogspot.com.br/2013/04/the-dark-side-of-asynctask.html

2016-11-12 16:58 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
Isso é ainda potencializado ainda mais, nos casos onde o Android decide recriar a Activity por causa de algum evento ( como por exemplo a rotação de tela). Nesse caso se a Async tiver sido criada antes da rotação, ela vai guardar a referência da Activity anterior, levando novamente a um memory leak.

> Losing your results
> Another problem is that we lose our results of the AsyncTask if our Activity has been recreated. For example when an orientation change occurs. The Activity will be destroyed and recreated, but our AsyncTask will now have an invalid reference to its Activity, so onPostExecute() will have no effect. There is a solution for this. You can hold onto a reference to AsyncTask that lasts between configuration changes (for example using a global holder in the Application object). Activity.onRetainNonConfigurationInstance() and Fragment.setRetainedInstance(true) may also help you in this case.

2016-11-12 17:30 UTC, fpbitencourt commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
Entendi! É que pra mim não tava claro que a AsyncTask sempre estava vinculada a uma activity. Estranho a documentação do Android não alertar os desenvolvedores para isso. Valeu pela information! Alterarei o código para Thread + Runnable.

2016-11-12 18:24 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/models/AppState.java
> +    }
If is the same why override? Finally is or isnt the same? The quality folder contains pmd supression file, but we have the annotation option too.

2016-11-14 18:53 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/asyncs/data/DataManager.java
> +    private class SaveAppStateTask extends AsyncTask<Void, Void, Boolean> {
É foda isso manolo. Eu descobri isso recente da pior maneira, debugando uns bugs loucos com fragments e async tasks. :disappointed:

2016-11-14 19:10 UTC, niltonvasques approved these changes

2016-11-15 21:18 UTC, raulccabreu commented
@fpbitencourt rebase with master and tests will pass.

2016-11-22 14:53 UTC, raulccabreu requested changes
Uma revisão adiantada...

2016-11-22 14:53 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/asyncs/data/DataManagerTest.java
> +        Map<String, Gif> gifs = new HashMap<>();
Mesmo que seu teste não esteja quebrando com HashMap, outro teste futuro pode quebrar, então é bom manter LinkedHashMap.

2016-11-22 14:53 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/MyApp.java
> +        mDataManager = new DataManager(getBaseContext());
Acho que mDataManager não precisa ser membro da classe, usa uma variável local lá no initializeFluxxan.

2016-11-22 14:53 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/middlewares/PersistenceMiddleware.java
> +        StateListener<AppState> {
No futuro o middleware vai ter um método "before" e "after" e vai deixar de ser um stateListener. Eu abriria uma issue pra mudar isso na Fluxxan.

2016-11-23 12:21 UTC, raulccabreu approved these changes

2016-11-23 12:22 UTC, raulccabreu commented
Approved 💯!

2016-11-23 12:24 UTC, niltonvasques commented
A lot of errors appear in the latest build on drone: 

```
br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendDownloadFailureAction STANDARD_ERROR
    Exception in thread "Thread-18" java.lang.UnsatisfiedLinkError: no snappydb-native in java.library.path
    	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    	at java.lang.System.loadLibrary(System.java:1122)
    	at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendPauseAction STANDARD_ERROR
    Exception in thread "Thread-20" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendLoadListAction STANDARD_ERROR
    Exception in thread "Thread-22" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenCompleteAppFlowActions STANDARD_ERROR
    Exception in thread "Thread-24" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendLoadListWithANonEmptyListAction STANDARD_ERROR
    Exception in thread "Thread-26" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendManyActions STANDARD_ERROR
    Exception in thread "Thread-28" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendPlayAction STANDARD_ERROR
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)
    Exception in thread "Thread-30" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendDownloadSuccessAction STANDARD_ERROR
    Exception in thread "Thread-32" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.GifListReducerTest > whenSendDownloadStartedAction STANDARD_ERROR
    Exception in thread "Thread-34" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
    	at java.lang.Thread.run(Thread.java:745)

br.com.catbag.gifreduxsample.reducers.reducers.AppStateReducerTest > initialAppState STANDARD_ERROR
    Exception in thread "Thread-36" java.lang.NoClassDefFoundError: Could not initialize class com.snappydb.internal.DBImpl
    	at com.snappydb.DBFactory.open(DBFactory.java:40)
    	at com.snappydb.DBFactory.open(DBFactory.java:65)
    	at com.snappydb.DBFactory.open(DBFactory.java:77)
    	at br.com.catbag.gifreduxsample.asyncs.data.storage.Database.saveAppState(Database.java:35)
    	at br.com.catbag.gifreduxsample.asyncs.data.DataManager$SaveAppStateRunnable.run(DataManager.java:164)
```

2016-11-23 12:47 UTC, raulccabreu commented
And the test passed? omg

2016-11-23 12:48 UTC, niltonvasques commented
Weird behavior! However the check task that also run unit tests have passed without errors.

2016-11-23 14:06 UTC, raulccabreu commented
Tried a second build/test and the same errors occurs.

2016-11-23 14:40 UTC, fpbitencourt commented
É um problema da RobolectricTestRunner com códigos nativos. 

Desregistrei os middlewares e fiz PersistenceMiddleware deixar de ouvir as mudanças do appstate para os testes do reducer e tá tudo certo agora.

2016-11-23 14:50 UTC, niltonvasques commented
Coverage has increased from 69% to 74% :dancer: :100: :smiley_cat:

2016-11-23 18:39 UTC, merged