Move async layer calls to middlewares
Catbag/redux-android-sample pull request #64
Opened 2016-11-15 19:04 UTC by niltonvasques

Now the action creators should only know how to create the right action and not call specific purpose class from the system.
The middlewares is best suited to handle those async operations.
An complete explanation can be found in the original [middlewares](http://redux.js.org/docs/advanced/Middleware.html) docs published by redux project.

* Add forked fluxxan module with middlewares feature
* Create two sample middlewares Logger and Analytics to test middlewares integration
* Create a rest middleware to intercept server actions and call server api
* Move async gifs download to rest middleware
* Move fetch logic from gif list Action Creator to RestMiddleware
* Adapt ui tests to replace rest middleware
* Attempt another strategy to preserver gh-pages history
* Create tests for rest middleware fetch gifs action
* Create a method in test helper for dispatch without await for state change
* Create tests for rest middleware gif download start with success and failure responses
* Test when dont has more gifs
* Create tests for when rest middleware intercept non useful actions

Fixes #54

2016-11-15 21:02 UTC, raulccabreu requested changes
Most wanted PR 👍 , now middware is on project and ActionCreator is clean and with one responsability!

2016-11-15 21:02 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);
2 lines with this code...`mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);`

2016-11-15 21:02 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        AppState state = ImmutableAppState.builder().build();
Put the ImmutableAppState.builder().build(); directly on the constructor if you want...

2016-11-15 21:02 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        Map params = (Map) mLastAction.Payload;
Action has a member with initial uppercase? O.o `mLastAction.Payload`

2016-11-15 21:02 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        RestMiddleware middleware = new RestMiddleware(RuntimeEnvironment.application,
If you want...import `RuntimeEnviroment` statically and put `mockDataManager();` directly on constructor....

2016-11-15 21:02 UTC, raulccabreu commented on settings.gradle
> +
Some requirement? O.o

2016-11-15 21:02 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/MyApp.java
>          AppState state = ImmutableAppState.builder().build();
Now we can extract a method, something like: `initializeFluxxan` or initializeReduxInfra`

2016-11-15 21:07 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);
Do you means this:

``` java
mHelper.getFluxxan()
            .getDispatcher()
            .unregisterMiddleware(RestMiddleware.class);
```

2016-11-15 21:07 UTC, niltonvasques commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        AppState state = ImmutableAppState.builder().build();
Which constructor?

2016-11-15 21:08 UTC, niltonvasques commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        Map params = (Map) mLastAction.Payload;
kkkk this comes from Fluxxan. We don't have control about it.

2016-11-15 21:10 UTC, niltonvasques commented on app/src/main/java/br/com/catbag/gifreduxsample/MyApp.java
>          AppState state = ImmutableAppState.builder().build();
But this method already is called initializeFluxxan.

2016-11-15 21:21 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);
Two occurrences of this line:

```
[here] mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);
Middleware restMiddleware = new RestMiddleware(getContext(), mock(DataManager.class),
              new FileDownloader());
[here] mHelper.getFluxxan().getDispatcher().unregisterMiddleware(RestMiddleware.class);
```

2016-11-15 21:22 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        AppState state = ImmutableAppState.builder().build();
`mFluxxan = new Fluxxan<>(state);`

2016-11-15 21:23 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        Map params = (Map) mLastAction.Payload;
This happens...soo much languages...this is probably C# memories LOL....kkkkkk

2016-11-15 21:24 UTC, raulccabreu commented on app/src/main/java/br/com/catbag/gifreduxsample/MyApp.java
>          AppState state = ImmutableAppState.builder().build();
KKKKKKKKKKKKKKKKKKKK, I'm dumb....relax

2016-11-15 22:15 UTC, niltonvasques commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        RestMiddleware middleware = new RestMiddleware(RuntimeEnvironment.application,
I can't put on constructor here, because dataManager is used below.

2016-11-15 22:32 UTC, niltonvasques commented
Your turn @raulccabreu!

2016-11-16 14:21 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +        RestMiddleware middleware = new RestMiddleware(RuntimeEnvironment.application,
Sorry....i see your comment but forget to reply. You`re right on your point. I don`t see the usage of `dataManager` below. Next time i will pay more attention on my PR revision. 👎 for me...

2016-11-16 14:29 UTC, raulccabreu requested changes
Sorry my bad revision....

2016-11-16 14:29 UTC, raulccabreu commented on app/src/test/java/br/com/catbag/gifreduxsample/reducers/middlewares/RestMiddlewareTest.java
> +                mockDataManager(), null);
Sorry....i see your comment but forget to reply. You`re right on your point. I don`t see the usage of `dataManager` below. Next time i will pay more attention on my PR revision. 👎 for me...

2016-11-16 20:58 UTC, raulccabreu approved these changes

2016-11-16 21:12 UTC, merged