Fix #85 and #45...
Catbag/redux-android-sample pull request #86
Opened 2016-11-25 19:07 UTC by raulccabreu

...with a endless scroll that fetchs on Rifty if "hasMoreGifs = true". The imported Gist class EndlessRecyclerScrollListener implements this behavior.

- Add a initialState method that initialize activity attributes based on initial AppState.
- Adjust some references to word "Component" (used before on FeedComponent and GifComponent) that now is only "View" following new naming of FeedView and GifView.
- Move the "package" net to inside package "data" where DataManager is the interface of the package as defined on planned architecture.
- Create the locker RecyclerTestLocker that lock based on RecyclerView's adapter size.
- Create the base class BaseTestLocker with common code between AnvilTestLocker and RecyclerTestLocker.
- Add the tests: "whenGifListIsEmpty", "whenGifListIsNotEmpty", "whenDefaultGifsAreLoaded", "whenEndlessScrollTriggered" and "whenEndlessScrollNotTriggered".
- Move some methods from GifListActivityTest to TestHelper and reuse this methods on other test classes.

2016-11-25 19:33 UTC, niltonvasques requested changes

2016-11-25 19:33 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +                .check(matches(withEffectiveVisibility(ViewMatchers.Visibility.VISIBLE)));
When the list is empty, the loading will run forever?

2016-11-25 19:33 UTC, niltonvasques commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +            db.destroy();
Which is the purpose of open and close database?

2016-11-25 19:55 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +                .check(matches(withEffectiveVisibility(ViewMatchers.Visibility.VISIBLE)));
If the AppState don't change, yes. But without mocks the activity calls the load action, and the Database populates with default gifs...if no previus AppState was saved.

2016-11-25 19:56 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +            db.destroy();
To destroy any traces of previous saved AppState on db.

2016-11-25 19:59 UTC, raulccabreu commented
The failure on build is some mock or AppState change leak between test cases.

2016-11-25 20:03 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +                .check(matches(withEffectiveVisibility(ViewMatchers.Visibility.VISIBLE)));
Em breve não teremos mais esse preenchimento automático, teremos que pensar em alguma abordagem para os casos que o appstate não seja carregado. Tipo exibir um dialog informando ao usuário com um botão para tentar novamente ou uma abordagem do loading + tentativas automáticas de recarregar o load até pegar algo do servidor.

2016-11-25 22:49 UTC, raulccabreu commented
Fixed! :+1:

2016-11-25 23:05 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +            db.close();
Faz mais sentido dar o close antes do destroy ou deixar somente o destroy caso o snappy garanta que feche o banco.

2016-11-25 23:05 UTC, fpbitencourt commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        mHelper.replacePersistenceMiddleware(new DataManager(getTargetContext()));
A definição dos middlewares não deveria vir antes de um dispatch?

2016-11-25 23:10 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +        mHelper.replacePersistenceMiddleware(new DataManager(getTargetContext()));
Nesse caso ai é melhor que esteja antes, porque esse dispatch ai é só aquele que envia pro fake reducer e "injeta" um estado inicial no Fluxxan, nesse caso um estado vazio só pra garantir que nesse caso de teste o app funcione como se fosse usado pela primeira vez. Então eu não queria que o middleware pegasse essa mudança de estado pra fazer algo inesperado.

2016-11-25 23:19 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +            db.close();
Pesquisando aqui, nos testes do SnappyDB o destroy tá sempre depois do close, e não é necessário ter o close antes, eles usam o destroy sem close tbm.

2016-11-25 23:24 UTC, raulccabreu commented on app/src/androidTest/java/br/com/catbag/gifreduxsample/ui/giflist/GifListActivityTest.java
> +            db.close();
Removi o close e comitei.

2016-11-25 23:29 UTC, fpbitencourt approved these changes
:+1:

2016-11-26 03:11 UTC, niltonvasques approved these changes

2016-11-26 12:19 UTC, merged